export const reports = [
            {
                id: 'b71376fd-015e-4209-99af-4543e82e5dc5',
                title: 'United States Government Configuration Baseline23',
                ref_id: 'xccdf_org.ssgproject.content_profile_ospp23',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:1,
                profile_title: 'PCI-DSS',
                os_major_version: '7',
            },
            {
                id: '719999b6-d230-4ba5-8dba-7ab3dc6561e0',
                title: 'PCI-DSS v3 Control Baseline for Red Hat Enterprise Linux 73',
                ref_id: 'xccdf_org.ssgproject.content_profile_pci-dss3',
                compliance_threshold: 68.9,
                business_objective: null,
                assigned_system_count:2,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'a440e363-b5a9-4a86-84e2-f6b3c9b56dc4',
                title: 'PCI-DSS v3.2.1 Control Baseline for Red Hat Enterprise Linux 7 - customized111',
                ref_id: 'xccdf_org.ssgproject.content_profile_pci-dss - customized111',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:1,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'dae0487d-3201-4ee0-af5f-b94cde2af818',
                title: 'United States Government Configuration Baseline2',
                ref_id: 'xccdf_org.ssgproject.content_profile_ospp2',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:4,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '8ed49cf9-16d4-4e49-9892-331b3c30919b',
                title: 'PCI-DSS v3 Control Baseline for Red Hat Enterprise Linux 8 - custom',
                ref_id: 'xccdf_org.ssgproject.content_profile_pci-dss_customized',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:7,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'dad42f58-bd06-42c1-986e-9195e951cee8',
                title: 'DISA STIG for Red Hat Enterprise Linux 7 - customized',
                ref_id: 'xccdf_org.ssgproject.content_profile_stig-rhel7-disa - customized',
                compliance_threshold: 92,
                business_objective: null,
                assigned_system_count:100,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '20a9d997-62a6-40cc-a5f3-19d466eb975e',
                title: 'C2S for Red Hat Enterprise Linux 7',
                ref_id: 'xccdf_org.ssgproject.content_profile_C2S',
                compliance_threshold: 69.5,
                business_objective: null,
                assigned_system_count:10,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'e4fe9d96-cf78-4f71-9831-db8240fe6477',
                title: 'United States Government Configuration Baseline - customized',
                ref_id: 'xccdf_org.ssgproject.content_profile_ospp - customized',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:15,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '9bd795d6-fdd7-4c4a-8fa5-13968be8984c',
                title: 'United States Government Configuration Baseline23',
                ref_id: 'xccdf_org.ssgproject.content_profile_osp23',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:23,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '6d345bd2-d597-4df8-9bcf-71c41155b42c',
                title: 'Criminal Justice Information Services (CJIS) Security Policy',
                ref_id: 'xccdf_org.ssgproject.content_profile_cjis',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:92,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'c8e15347-9c2b-495d-8e54-503c2f9582b6',
                title: 'Unclassified Information in Non-federal Information Systems and Organizations (NIST 800-171)',
                ref_id: 'xccdf_org.ssgproject.content_profile_nist-800-171-cui',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:44,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '3c4823a1-2c16-46ae-b2fe-0cebf5a03931',
                title: 'PCI-DSS v3 Control Baseline for Red Hat Enterprise Linux 7',
                ref_id: 'xccdf_org.ssgproject.content_profile_pci-dss',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:23,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'f7b7977a-403b-4cd1-ab90-20b6f9a5a359',
                title: 'Red Hat Corporate Profile for Certified Cloud Providers (RH CCP)',
                ref_id: 'xccdf_org.ssgproject.content_profile_rht-ccp',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:1,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '36abc364-6dc3-4e35-94f4-d10fa77e866e',
                title: 'Health Insurance Portability and Accountability Act (HIPAA)',
                ref_id: 'xccdf_org.ssgproject.content_profile_hipaa',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:3,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'd35c8aad-8fc8-49e8-bff0-4d9d3dc8f220',
                title: 'United States Government Configuration Baseline',
                ref_id: 'xccdf_org.ssgproject.content_profile_ospp',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:9,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
        {
                id: '4c27fe09-9a7f-437c-b38b-e42272d9ccf0',
                title: 'Standard System Security Profile for Red Hat Enterprise Linux 7',
                ref_id: 'xccdf_org.ssgproject.content_profile_standard',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:33,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '9b034440-e3dd-4c19-8f2c-ca75e813d57d',
                title: 'DISA STIG for Red Hat Enterprise Linux 7',
                ref_id: 'xccdf_org.ssgproject.content_profile_stig-rhel7-disa',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:44,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: '19921ca4-8526-4651-8876-3c8587e8e125',
                title: 'PCI-DSS v3 Control Baseline for Red Hat Enterprise Linux 72',
                ref_id: 'xccdf_org.ssgproject.content_profile_pci-dss2',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:233,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            },
            {
                id: 'fcfa7e62-eebe-4cbc-8583-d4c2e0bb3ccc',
                title: 'DISA STIG for Red Hat Enterprise Linux 7 - customized23',
                ref_id: 'xccdf_org.ssgproject.content_profile_stig-rhel7-disa - customized23',
                compliance_threshold: 100,
                business_objective: null,
                assigned_system_count:232,
                profile_title: 'PCI-DSS',
                os_major_version: '8',
            }
        ];
