parser: '@babel/eslint-parser'
extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:cypress/recommended'
  - "plugin:testing-library/react"
  - "plugin:jest-dom/recommended"

globals:
  React: true

rules:
   rulesdir/forbid-pf-relative-imports: 'off'
