parser: '@babel/eslint-parser'
extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:cypress/recommended'
  - "plugin:testing-library/react"
  - "plugin:jest-dom/recommended"

globals:
  beforeAll: true
  describe: true
  expect: true
  global: true
  insights: true
  it: true
  mount: true
  process: true
  render: true
  shallow: true
  React: true
  Promise: true
  toJson: true
  renderJson: true
