parser: babel-eslint
extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:cypress/recommended'
globals:
  beforeAll: true
  describe: true
  expect: true
  global: true
  insights: true
  it: true
  process: true
  React: true
  Promise: true
