parser: '@babel/eslint-parser'
plugins:
  - jsdoc
extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:cypress/recommended'
  - "plugin:testing-library/react"
  - "plugin:jest-dom/recommended"
  - "plugin:jsdoc/recommended"

globals:
  React: true

rules:
   rulesdir/forbid-pf-relative-imports: 'off'
   jsdoc/tag-lines: 0
   jsdoc/require-jsdoc: 0

