export const FETCH_COMPLIANCE_POLICIES = 'FETCH_COMPLIANCE_POLICIES';
export const FETCH_COMPLIANCE_POLICY_DETAILS = 'FETCH_COMPLIANCE_POLICY_DETAILS';
export const FETCH_COMPLIANCE_SYSTEMS = 'FETCH_COMPLIANCE_SYSTEMS';
export const FETCH_COMPLIANCE_SYSTEMS_FOR_POLICY = 'FETCH_COMPLIANCE_SYSTEMS_FOR_POLICY';
