apiVersion: v1
kind: Pod
metadata:
  labels:
    name: jenkins-slave-iqe
spec:
  containers:
  - image: docker-registry.default.svc:5000/jenkinsstg/selenium-fc29:latest
    name: selenium
    resources:
      limits:
        cpu: 300m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 2Gi
  - image: docker-registry.default.svc:5000/jenkinsstg/jenkins-slave-iqe:latest
    name: jnlp
    args:
      - "$(JENKINS_SECRET)"
      - "$(JENKINS_NAME)"
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
  dnsPolicy: ClusterFirst
